### PR TITLE
Feature/fix several typos

### PR DESCRIPTION
**Pull request by lootsy**
Hello again,

second try. If I should change / adopt something please let me know.
Thx!

Kind regards, Ludger

### CODE REVIEW

**Comment by simondueckert** [comment]
Very good suggestions, I try to  handle them next monday.

**Comment by lootsy** [comment]
No need to hurry. Just wanted to ask for the current state.
Thx for __your__ contribution.

**Comment by lootsy** [comment]
It seems that there aren't any (merge) conflicts anymore.
Feel free to merge my changes into your master branch.

Otherwise: Please let me know how can I get these changes incorporated.
Thx!

**Comment by lootsy** [comment]
I will revert my mistake, therefore I close this PR.
Sorry for any inconvenience.

**Pull request closed without merging**
